### ISSUE TITLE
Browser Only?

### ISSUE THREAD

**Issue by calebboyd** [ibc/WebSocketWrapper#1]
First, Thanks for your work on this, its really handy.
 
I've been using it for quite a while. I was wondering if the the intent to drop all node support in 1.0.0? I was wanting to upgrade (from 0.2.2) and noticed that it is now relying on DOM apis `WebSocket` and `document`. Any plans to support Node? PRs welcome? Thanks.

**Comment by calebboyd** [comment]
ping!

**Comment by ibc** [comment]
Sorry, I missed this issue.

Honestly I don't plan to maintain this library any more. I think that managing reconnection stuff is better achieved by specific applications with their specific needs.

In fact, recently I've switched to [retry](https://www.npmjs.com/package/retry) (see my usage [here](https://github.com/ibc/protoo/blob/master/client/lib/transports/WebSocketTransport.js)).

BTW I removed Node support because it requires the [websocket](https://www.npmjs.com/package/websocket) library, which requires C/C++ compilation and takes long time, which was a bit ugly when using this library to build browser side apps.

**Comment by calebboyd** [comment]
Fair enough. Thanks!
